# Generated by Django 6.0.3 on 2026-03-10 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_alter_categorydb_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryDb',
        ),
    ]
