# Generated by Django 6.0.3 on 2026-03-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminApp', '0003_delete_categorydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddcategoryDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
