# Generated by Django 6.0.3 on 2026-03-10 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdb',
            old_name='username',
            new_name='Username',
        ),
    ]
