# Generated by Django 6.0.3 on 2026-03-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_rename_username_userdb_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=150)),
                ('Mobile', models.CharField(max_length=20)),
                ('Description', models.TextField()),
            ],
        ),
    ]
