# Generated by Django 6.0.3 on 2026-03-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_contactdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='issues')),
                ('Description', models.TextField()),
                ('Contact_Number', models.CharField(max_length=20)),
                ('Latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('Longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('Location', models.CharField(max_length=255)),
                ('Created_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
