# Generated by Django 6.0.3 on 2026-03-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_issuedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField()),
            ],
        ),
    ]
