# Generated by Django 6.0.3 on 2026-03-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_commentdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentdb',
            name='Username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
