# Generated by Django 6.0.3 on 2026-03-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_commentdb_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedb',
            name='Username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
