# Generated by Django 6.0.3 on 2026-03-10 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_issuedb_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentdb',
            name='Issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='WebApp.issuedb'),
        ),
    ]
