# Generated by Django 6.0.3 on 2026-03-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_commentdb_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedb',
            name='Status',
            field=models.CharField(choices=[('unsolved', 'Unsolved'), ('in_progress', 'In Progress'), ('solved', 'Solved')], default='unsolved', max_length=20),
        ),
    ]
